# Generated by Django 5.2.7 on 2025-11-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='blogimages',
            name='image',
            field=models.FileField(upload_to='blog'),
        ),
    ]
